version: "2.1"
services:
  postgres:
    image: postgres:18-alpine@sha256:d3e1620b530c944afa6e887d22eb899824da68e19c52024bf98f5220c88a65b2
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
      TZ: UTC
    ports:
      - "5431:5432"
    command:
      - -c
      - synchronous_commit=off
      - -c
      - fsync=off
      - -c
      - full_page_writes=off
  minio-server:
    image: pgsty/minio:RELEASE.2026-08-04T00-00-00Z
    environment:
      MINIO_ROOT_USER: USERNAME
      MINIO_ROOT_PASSWORD: PASSWORD
    command: server /data --console-address ":9001"
    ports:
      - "43680:9000"
      - "43697:9001"
  minio-client:
    image: pgsty/mc:RELEASE.2026-09-13T00-00-00Z
    depends_on:
      - minio-server
    entrypoint: >
      /bin/sh -c "
      set -e;
      sleep 1;
      /usr/bin/mc alias set minio-server http://minio-server:9000 USERNAME PASSWORD;
      /usr/bin/mc mb --ignore-existing minio-server/balena-pine-web-resources;
      sleep infinity;
      "
