// Generated by CoffeeScript 1.3.3
(function() {

  define(['data-frame/widgets/text', 'data-frame/widgets/textArea', 'data-frame/widgets/foreignKey', 'data-frame/widgets/integer', 'data-frame/widgets/boolean'], function(text, textArea, foreignKey, integer, boolean) {
    var widgets;
    widgets = {};
    widgets.text = text;
    widgets.textArea = textArea;
    widgets.foreignKey = foreignKey;
    widgets.integer = integer;
    widgets.boolean = boolean;
    return widgets;
  });

}).call(this);
