INSERT INTO "pilot" ("id","value", "is experienced") values ('1','Joachim','1');
INSERT INTO "pilot" ("id","value") values ('2','Esteban');
INSERT INTO "plane" ("id","value") values ('1','Boeing 747');
INSERT INTO "plane" ("id","value") values ('2','Spitfire');
INSERT INTO "plane" ("id","value") values ('3','Concorde');
INSERT INTO "plane" ("id","value") values ('4','Mirage 2000');
INSERT INTO "pilot-can_fly-plane" ("id","pilot","plane") values ('1','1','2');
INSERT INTO "pilot-can_fly-plane" ("id","pilot","plane") values ('2','1','3');
INSERT INTO "pilot-can_fly-plane" ("id","pilot","plane") values ('3','1','4');
INSERT INTO "pilot-can_fly-plane" ("id","pilot","plane") values ('4','2','1');
