// These types were generated by @balena/abstract-sql-to-typescript v6.1.2

import type { Types } from '@balena/abstract-sql-to-typescript';

export interface MultipartUpload {
	Read: {
		created_at: Types['Date Time']['Read'];
		modified_at: Types['Date Time']['Read'];
		id: Types['Serial']['Read'];
		uuid: Types['Short Text']['Read'];
		resource_name: Types['Short Text']['Read'];
		field_name: Types['Short Text']['Read'];
		resource_id: Types['Integer']['Read'];
		upload_id: Types['Short Text']['Read'];
		file_key: Types['Short Text']['Read'];
		status: 'pending' | 'completed' | 'cancelled';
		filename: Types['Short Text']['Read'];
		content_type: Types['Short Text']['Read'];
		size: Types['Big Integer']['Read'];
		chunk_size: Types['Integer']['Read'];
		expiry_date: Types['Date Time']['Read'];
		is_created_by__actor: Types['Integer']['Read'] | null;
	};
	Write: {
		created_at: Types['Date Time']['Write'];
		modified_at: Types['Date Time']['Write'];
		id: Types['Serial']['Write'];
		uuid: Types['Short Text']['Write'];
		resource_name: Types['Short Text']['Write'];
		field_name: Types['Short Text']['Write'];
		resource_id: Types['Integer']['Write'];
		upload_id: Types['Short Text']['Write'];
		file_key: Types['Short Text']['Write'];
		status: 'pending' | 'completed' | 'cancelled';
		filename: Types['Short Text']['Write'];
		content_type: Types['Short Text']['Write'];
		size: Types['Big Integer']['Write'];
		chunk_size: Types['Integer']['Write'];
		expiry_date: Types['Date Time']['Write'];
		is_created_by__actor: Types['Integer']['Write'] | null;
	};
}

export default interface $Model {
	multipart_upload: MultipartUpload;
}
