// Generated by CoffeeScript 1.3.3
(function() {
  var __slice = [].slice;

  define(function(requirejs, exports, module) {
    var app;
    app = (function() {
      var addHandler, handlers;
      handlers = {
        POST: [],
        PUT: [],
        DELETE: [],
        GET: []
      };
      addHandler = function() {
        var handlerName, match, middleware, paramMatch, paramName, _ref;
        handlerName = arguments[0], match = arguments[1], middleware = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
        match = match.replace(/[\/\*]*$/, '');
        paramMatch = /:(.*)$/.exec(match);
        paramName = (_ref = paramMatch === null) != null ? _ref : {
          "null": paramMatch[1]
        };
        return handlers[handlerName].push({
          match: match,
          paramName: paramName,
          middleware: middleware
        });
      };
      return {
        post: function() {
          var args;
          args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          return addHandler.apply(null, ['POST'].concat(args));
        },
        get: function() {
          var args;
          args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          return addHandler.apply(null, ['GET'].concat(args));
        },
        put: function() {
          var args;
          args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          return addHandler.apply(null, ['PUT'].concat(args));
        },
        del: function() {
          var args;
          args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          return addHandler.apply(null, ['DELETE'].concat(args));
        },
        all: function() {
          this.post.apply(this, arguments);
          this.get.apply(this, arguments);
          this.put.apply(this, arguments);
          return this.del.apply(this, arguments);
        },
        process: function(method, uri, headers, body, successCallback, failureCallback) {
          var checkMethodHandlers, i, j, methodHandlers, next, req, res;
          if (body == null) {
            body = '';
          }
          if (!handlers[method]) {
            failureCallback(404);
          }
          req = {
            method: method,
            body: body,
            headers: headers,
            url: uri,
            params: {}
          };
          console.log(method, uri, body);
          if (uri.slice(-1) === '/') {
            uri = uri.slice(0, uri.length - 1);
          }
          uri = uri.toLowerCase();
          res = {
            json: function(obj, headers, statusCode) {
              var _ref;
              if (headers == null) {
                headers = 200;
              }
              if (typeof headers === 'number' && !(statusCode != null)) {
                _ref = [headers, {}], statusCode = _ref[0], headers = _ref[1];
              }
              obj = JSON.parse(JSON.stringify(obj));
              if (statusCode === 404) {
                return failureCallback(statusCode, obj, headers);
              } else {
                return successCallback(statusCode, obj, headers);
              }
            },
            send: function(statusCode, headers) {
              if (statusCode === 404) {
                return failureCallback(statusCode, null, headers);
              } else {
                return successCallback(statusCode, null, headers);
              }
            },
            redirect: function() {
              return failureCallback(307);
            }
          };
          next = function(route) {
            j++;
            if (route === 'route' || j >= methodHandlers[i].middleware.length) {
              return checkMethodHandlers();
            } else {
              return methodHandlers[i].middleware[j](req, res, next);
            }
          };
          methodHandlers = handlers[method];
          i = -1;
          j = -1;
          checkMethodHandlers = function() {
            i++;
            if (i < methodHandlers.length) {
              if (uri.slice(0, methodHandlers[i].match.length) === methodHandlers[i].match) {
                j = -1;
                if (methodHandlers[i].paramName !== null) {
                  req.params[methodHandlers[i].paramName] = uri.slice(methodHandlers[i].match.length);
                }
                return next();
              } else {
                return checkMethodHandlers();
              }
            } else {
              return res.send(404);
            }
          };
          return checkMethodHandlers();
        }
      };
    })();
    return {
      app: app
    };
  });

}).call(this);
