define(['cs!frame-glue/glue', 'cs!sbvr-lf/lfviz'], (glue, lfviz) ->
	json = """
	["Model",
	["Term",
		"pilot",
		[]],
	["Term",
		"plane",
		[]],
	["FactType",
		["Term",
			"pilot"],
		["Verb",
			"can fly"],
		["Term",
			"plane"],
		[]],
	["FactType",
		["Term",
			"pilot"],
		["Verb",
			"is experienced"],
		[]],
	["Rule",
		["ObligationF",
			["UniversalQ",
				["Variable",
					["Number",
						0],
					["Term",
						"pilot"]],
				["AtLeastNQ",
					["MinimumCardinality",
						["Number",
							1]],
					["Variable",
						["Number",
							1],
						["Term",
							"plane"]],
					["AtomicFormulation",
						["FactType",
							["Term",
								"pilot"],
							["Verb",
								"can fly"],
							["Term",
								"plane"]],
						["RoleBinding",
							["Term",
								"pilot"],
							0],
						["RoleBinding",
							["Term",
								"plane"],
							1]]]]],
		["StructuredEnglish",
			"It is obligatory that each pilot can fly at least 1 plane"]],
	["Rule",
		["ObligationF",
			["UniversalQ",
				["Variable",
					["Number",
						0],
					["Term",
						"pilot"],
					["AtomicFormulation",
						["FactType",
							["Term",
								"pilot"],
							["Verb",
								"is experienced"]],
						["RoleBinding",
							["Term",
								"pilot"],
							0]]],
				["AtLeastNQ",
					["MinimumCardinality",
						["Number",
							3]],
					["Variable",
						["Number",
							1],
						["Term",
							"plane"]],
					["AtomicFormulation",
						["FactType",
							["Term",
								"pilot"],
							["Verb",
								"can fly"],
							["Term",
								"plane"]],
						["RoleBinding",
							["Term",
								"pilot"],
							0],
						["RoleBinding",
							["Term",
								"plane"],
							1]]]]],
		["StructuredEnglish",
			"It is obligatory that each pilot that is experienced can fly at least 3 planes"]]]"""

	return {
		init: ->
			content = glue('LF')
			lfviz(json, content)
	}
)
