// These types were generated by @balena/abstract-sql-to-typescript v5.1.0

import type { Types } from '@balena/abstract-sql-to-typescript';

export interface Student {
	Read: {
		created_at: Types['Date Time']['Read'];
		modified_at: Types['Date Time']['Read'];
		id: Types['Serial']['Read'];
		name: Types['Short Text']['Read'];
		semester: Types['Integer']['Read'];
		is_repeating: Types['Boolean']['Read'];
		previous_year_grade: Types['Short Text']['Read'] | null;
	};
	Write: {
		created_at: Types['Date Time']['Write'];
		modified_at: Types['Date Time']['Write'];
		id: Types['Serial']['Write'];
		name: Types['Short Text']['Write'];
		semester: Types['Integer']['Write'];
		is_repeating: Types['Boolean']['Write'];
		previous_year_grade: Types['Short Text']['Write'] | null;
	};
}

export default interface $Model {
	student: Student;
}
