name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [main, master]
  push:
    branches: [main, master]

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@master # flowzonify 0.4.0
    secrets: inherit
